### ISSUE TITLE
Flavor text does not match form controls

### ISSUE THREAD

**Issue by peteykun** [InternetFreedomFoundation/internetfreedom.in#1]
On the [support](https://internetfreedom.in/support/) page, the flavor text for the checkbox "I’d like to volunteer my time and skills" reads "Please check any specific areas you can help with." (which would imply that you can pick multiple skills), however the form control for picking said areas are radio buttons and not check boxes.

![image](https://user-images.githubusercontent.com/3918319/29488269-feeab712-8524-11e7-9cfc-7e96c26c9246.png)

Either the flavor text or the form controls need to change for consistency.

**Comment by karthikb351** [comment]
Thanks for pointing this out. I've updated the [support page](https://internetfreedom.in/support/).
