### ISSUE TITLE
Typo in footer

### ISSUE THREAD

**Issue by sujaldev** [InternetFreedomFoundation/internetfreedom.in#17]
The Linkedin URL in the footer of [internetfreedom.in](https://internetfreedom.in/) has a typo: `hhttps` -> `https`. Please consider publishing the source code for the website.

**Comment by anoop-b** [comment]
Thank you for flagging this. you can find the source over [here](https://github.com/InternetFreedomFoundation/internetfreedom.in/tree/dev).

**Comment by anoop-b** [comment]
fixed in 256e7f8602ca923d16718313ce188c817b257bca
