### ISSUE TITLE
Featured image

### ISSUE THREAD

**Issue by anoop-b** [InternetFreedomFoundation/internetfreedom.in#9]
Since a majority of the posts do not contain featured image, we can skip the featured image part in the blog view. Only render the blog html.

**Comment by anoop-b** [comment]
@ameen4455 might wanna take this up

**Comment by ameen4455** [comment]
What about the blog list thumbnail for those blogs?

**Comment by anoop-b** [comment]
Something like this should work?
```
{post.feature_image || post.og_image}
```

**Comment by anoop-b** [comment]
Some posts seem to have `og_image` but aren't loading for some reason. Any idea why?
